language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - node -v
        - npm install -g danger
        - swift build
        - make install
      script:
        - swift test
        # - DEBUG="*" danger process .build/x86_64-apple-macosx10.10/debug/danger-swift
        # - DEBUG="*" danger ci --process .build/x86_64-apple-macosx10.10/debug/danger-swift
        # - sudo chmod -R a+rwx /usr/local/Cellar/
        # - DEBUG="*" danger-swift ci
        # - DEBUG="*" .build/x86_64-apple-macosx10.10/debug/danger-swift ci
        - .build/x86_64-apple-macosx10.10/debug/danger-swift ci

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 4.2
        - swift build
      script:
        - swift test
        - sudo chmod -R a+rwx /usr/local/
        - make install
        - DEBUG="*" danger-swift ci
