cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift

language: generic

matrix:
  include:
    - os: osx
      name: Swift 5.0
      osx_image: xcode10.2
      install:
        - node -v
        - npm install -g danger
        - make install
      script:
        - danger-swift ci

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1-DEVELOPMENT-SNAPSHOT-2019-05-09-a
      script:
        - swift build
        #- DEBUG='*' swift run danger-swift ci
