cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11
      install:
        - node -v
        - npm install -g danger@7.1.4
        - make install
      script:
        - swift test
        - danger-swift ci

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger@7.1.4
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1-DEVELOPMENT-SNAPSHOT-2019-09-18-a
      script:
        - swift test
        - sudo chmod -R a+rwx /usr/local/
        - make install
        - DEBUG="*" danger-swift ci

    - os: osx
      name: Danger with SPM
      osx_image: xcode11
      install:
        - node -v
        - npm install -g danger@7.1.4
      script:
        - swift run danger-swift ci

    - os: linux
      name: Danger with SPM
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger@7.1.4
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1-DEVELOPMENT-SNAPSHOT-2019-09-18-a
      script:
        - swift run danger-swift ci
