cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift
    - ~/.swiftenv

language: generic

matrix:
  include:
    - os: osx
      name: Swift 5.0
      osx_image: xcode10.2
      install:
        - node -v
        - npm install -g danger
        - make install
      script:
        - danger-swift ci

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1-DEVELOPMENT-SNAPSHOT-2019-05-29-a
      script:
        - DEBUG='*' swift run danger-swift ci

    - os: linux
      name: Make install
      language: generic
      sudo: required
      dist: trusty
      install:
        - node -v
        - npm install -g danger
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1-DEVELOPMENT-SNAPSHOT-2019-05-29-a
        - sudo chmod -R a+rwx /usr/local/
        - make install
      script:
        - danger-swift ci
