name: Release Danger-Swift package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Export tag version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    
    - name: Docker Login
      run: echo $PACKAGES_WRITE_TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
      env:
        PACKAGES_WRITE_TOKEN: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
        USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}

    - name: Docker Build
      run: docker build -t ghcr.io/danger/danger-swift:$VERSION .

    - name: Deploy
      run: docker push ghcr.io/danger/danger-swift:$VERSION

    - name: Update Dockerfile to create image with Swiftlint
      run: Scripts/release_swiftlint_docker.sh
    
    - name: Docker Build
      run: docker build -t ghcr.io/danger/danger-swift-with-swiftlint:$VERSION .

    - name: Deploy
      run: docker push ghcr.io/danger/danger-swift-with-swiftlint:$VERSION
